### ISSUE TITLE
GTM tracks Distributor, but not the rest of the website

### ISSUE THREAD

**Issue by jirihelmich** [MewsSystems/public#17]
Hotel has 2 websites, one is being tracked completely, but the second one tracks only Distributor events. 

> If you need access to our GTM or Analytics from other account, please let me know.
> As I have said, on M. analytics tag is fired properly on all pages, on M2 though, the tag fires only when you open the distributor.
> I have made a workaround where "Analytics 1" tag fires on all distributor events and "Analytics 2" tag fires on all pageviews besides the ones with distributor trigger. Do not think it is a good way to do it but it was the only solution I could think of.
> 1. What couses this difference when everything is set up the same? Can you look into it?
> 2. I have set up "allowLinker" to true but still the attribution model in analytics shows all the conversions as direct from mews.li (payment gate). What else can we do?

**Comment by fickomat** [comment]
Any news?

**Comment by pbambusek** [comment]
No event from Distributor will be fired until the Distributor is initialized; this happens only after you opened it for the first time. That is intentional and correct, because many events can potentially happen on background, but doesn't make sense to track them if they weren't triggered by user. Also there is no reason in loading the application if the user is not interacting with it.

Can you elaborate more on what you're trying to track?  I'm not really sure that I understand it correctly, but If you're trying to track something on a website, then it has nothing to do with Distributor. Why are you asking us to solve it? Have you included the GTM tracking snippet into a website? We really can't help you with that, you should turn to a GTM documentation with a generic issue.

I don't know how attribution in analytics work exactly, but I know that we aren't really making any effort to look it differently. The transaction itself happens on mews.li domain and that's how it's reported. Why should it be any different? The `allowLinker` option has as far as I know no impact on this.

**Comment by fickomat** [comment]
We have MO and MH website.
/ First part I understand
/ Of course we want to track both distributor events and non-distributor pageviews in Analytics. Before your edit, we were using pageviews for Universal Analytics to track everything and you have changed it to events so I though it has some reason.
/ Of course we have a GTM snippet included on the websites, we would not track anything without it would we?
/ Third part I will ellaborate bellow

Again to both problems:

1. GTM trigger problem
Both websites use this implementation for Google analytics implementation
![image](https://cloud.githubusercontent.com/assets/15713916/25872909/b599ea78-350c-11e7-96d5-5a964d322d66.png)

When i load the homepage:
- on MO, tag is triggered and I can see it in "preview" mode in GTM and I can aslo see the pageview in Analytics ( I do not understend why there is any event that triggers it here in a fist place ).
- on MH. tag is not triggered on homepage
- same situation is on lets say /apartments or /gallery or any other non-distributor page
- when I click "book now" and initialze the distributor, the tag is fired correctly on both

As a solution, I have created another tag in GTM on MH, which is fired on all pageviews except the ones where distributorEvents are triggered. It seems to work well.
- I suppose that this solution is a correct approach. Is it?
- Why does it work differently on each site? Does the distributor preload on homepage on MO (and not on MH) for some reason?

2. Attribution

- User comes from a source1 (reffered as paid visit in Analytics). We can clearly see all refferals when we check the channels in universal analytics. We see, that for example 50 users came from campaign called "special promo"
- However, we need to know, how many of them have finished the booking and what are the ecommerce values for their visits, so we can evaluate the campaign.
- We now do have the ecommerce data passing through GTM succesfully, thanks to the GTM tag being implemented on mews.li domain as well.
- All this conversions appears to be coming from mews.li now (where the actual conversion happen) but it is irrelevant, because we need to know the original source.
- There is some problem with linker and cross domain tracking I suppose
Here are some explanations, that might help>
http://www.lunametrics.com/blog/2015/06/16/cross-domain-tracking-with-google-tag-manager/
https://www.optimizesmart.com/cross-domain-tracking-in-google-tag-manager/

**Comment by pbambusek** [comment]
We haven't "changed it to events", tracking with events is there from begining. What you might have on mind is a deprecated and redundant subset of events called `hashEvents`, that were adding fragments to an url on step changes. These can't cover the whole range of data and actions covered by events. How would you do it for i.e. multi hotel sequence of availability load for all hotels? How would pass any data through it? 

Tracking a pageview doesn't happen automatically, you have to trigger it. Distributor has never triggered a pageview events by itself. Analytics tracking code have this usually included, GTM does not, because it wouldn't make a sense. Are you sure you haven't removed it from website, without adding it to the container?

I'm still not sure what you're trying to track, is it those pageviews? I don't know why do you think Distributor should trigger any event on a website where there is no Distributor, ergo there is no code that would trigger the event?

> on MO, tag is triggered and I can see it in "preview" mode in GTM and I can aslo see the pageview in > Analytics ( I do not understend why there is any event that triggers it here in a fist place ).
> on MH. tag is not triggered on homepage
> same situation is on lets say /apartments or /gallery or any other non-distributor page
> when I click "book now" and initialze the distributor, the tag is fired correctly on both

In light of the "first part" you understood, why do you think that there is some incorrect behaviour?

Once more, Distributor triggers only those events, nothing more. If you want to track anything else, you have to do it on your own. So, yes, if it works for your problem, it's an solution. 

Can you confirm that both of those websites have exactly the same configuration and exactly the same content, containers, tags, ... ?

I don't see any problem from Distributor point of view in this so far.

**Comment by pbambusek** [comment]
I've moved the attribution question here #18

**Comment by fickomat** [comment]
Petr, I do understand how it should work and I do know that it needs a trigger.
Lets forget about who changed who and lets find a solution.

> I'm still not sure what you're trying to track, is it those pageviews? I don't know why do you think Distributor should trigger any event on a website where there is no Distributor, ergo there is no code that would trigger the event?

Well, it does on MO! I have no idea why. This is preview mode on homepage ( and it is same on /apartments etc )

![image](https://cloud.githubusercontent.com/assets/15713916/25945682/25e68a02-3648-11e7-8825-157f1b5fd6d6.png)

I have already sent you this or similar printscreen couple of times. Why is the analytics tag fired if it is set up like this??

![image](https://cloud.githubusercontent.com/assets/15713916/25945798/83386bc6-3648-11e7-8b2d-0e0208097dd2.png)

Tracking id is blured out for security but it is correct.
Event name is set to ^distributor

Tag and trigger are same for both websites.
When we can make this tag fire only in distributor, I can create second tag for pageviews ( like i did on MH) and we can move on.

You say it should not be triggered here, but it is. Why?

**Comment by pbambusek** [comment]
Ok, now I finally see the difference. On MO website, you use `defaultLanguage` option, while on MH you don't. The default language is set as part of initial configuration, which is the only operation which happens before the app initialization. GTM integration currently does not wait correctly for the initialization to happen, and triggers this event immediately.

I'll create an issue for this check to be added, so this event won't leak before the initialization.

However, as you set the language to `en-GB` which is the default language of Distributor anyway, you can freely remove this option for same behaviour.

**Comment by pbambusek** [comment]
The initialization was fixed last week: https://github.com/MewsSystems/public/blob/gh-pages/content/developers/distributor/widget/changelog.md#24052017
