### ISSUE TITLE
GTM doesn't propagate attribution correctly for Merchant integration

### ISSUE THREAD

**Issue by pbambusek** [MewsSystems/public#19]
Forked from #17 

The attribution model in analytics shows all the conversions as direct from mews.li (payment gate). What else can we do?

2. Attribution

- User comes from a source1 (reffered as paid visit in Analytics). We can clearly see all refferals when we check the channels in universal analytics. We see, that for example 50 users came from campaign called "special promo"
- However, we need to know, how many of them have finished the booking and what are the ecommerce values for their visits, so we can evaluate the campaign.
- We now do have the ecommerce data passing through GTM succesfully, thanks to the GTM tag being implemented on mews.li domain as well.
- All this conversions appears to be coming from mews.li now (where the actual conversion happen) but it is irrelevant, because we need to know the original source.
- There is some problem with linker and cross domain tracking I suppose
Here are some explanations, that might help>
http://www.lunametrics.com/blog/2015/06/16/cross-domain-tracking-with-google-tag-manager/
https://www.optimizesmart.com/cross-domain-tracking-in-google-tag-manager/

**Comment by pbambusek** [comment]
Ok, I understand what you want to track. Now, have you configured your container in a way that i.e. the first link suggests? Or, in another words, what do you expect from us that could solve the issue?

One think I can tell is that this is caused by the redirect done for Merchant integration, however this will be removed in near future with migration to Stripe. After that, it should work just ok without any change needed I guess.

**Comment by fickomat** [comment]
I have double checked and created a new view in analytics but all conversions are still reffered as direct traffic from here:

![image](https://cloud.githubusercontent.com/assets/15713916/25996581/4aec4ffa-3718-11e7-8e75-de6f4d38b31a.png)

One big difference to the approach described in first link is that it is design for "pageview" method, not "event" based tracking. 

As I said, on MH, I have now two tags, one is for pageviews and one is for events.

The one for pageviews is set exactly like in a first link.
The one for events is missing the fields called "cross domain tracking" so I could not set those.
Analytics view is set according to the first link as well with refferall exclusion and passing domain name (link 2).

**Comment by pbambusek** [comment]
I'm not sure if there is anything on Distributor side that we could improve apart removing the redirect. As far as I understand those articles, it's all based on GTM and Analytics settings, which are both directly in your control.

As I have said, we're preparing an update that will remove the need for redirects in checkout process. If you have no suggestion on a possible fix, I'd like to ask you to wait until the removal happens.

**Comment by fickomat** [comment]
Any ETA when will the update be available?

**Comment by pbambusek** [comment]
I can't give you any ETA as there is none yet. When it's implemented, the issue will be updated to notify you.

**Comment by matthijswelle** [comment]
We are not planning to move hotels in Czech Republic to Stripe, as they do not support CZK (yet). 

So Mosaic House and MOOo will remain with Adyen and thus we have to keep the redirect to Mews.li to capture the credit card details still as that is required by them.

Unfortunately we do not see any way to resolve this in the short term. :-( Fingers crossed that Stripe enters this market sooner.

**Comment by matusficko** [comment]
I do not understand where the problem is with cross-doman tracking. Can you explain it to me?
This is crucial for any performance analysis.

There are implementations even for iframes CDT like this one:
https://www.simoahava.com/analytics/iframe-cross-domain-tracking-in-google-tag-manager/
It uses callBack function to force override the clientID in analytics tag.
Can we use something similar?

What exactly is causing the allowLinker not to override the clientId?
1. If I understand correctly, the distributor is running since the initialisation on the mews.li domain parallel with ours and is just being loaded to our domain (similar to iframe). Is it true?
2. Can it have something to do with 2 gtm containers being used simultaneously? Cookie- conflict?

There must be a solution to this

**Comment by pbambusek** [comment]
1. No, Distributor runs on your domain, then serializes its state, sends it to our domain, where new Distributor is created and hydrated with the state received.

The redirect does not happen in the iframe, it happens in the top window, otherwise it wouldn't make a sense.

2. Don't belive so, the cookies are keyed by container and account ids.

I might try to use the linker manually for redirect, though I'm not sure how will that work with GTM.

**Comment by matusficko** [comment]
I will be very happy to assist you with the testing anytime if it is of any help.
Just let me know how.

**Comment by matusficko** [comment]
@pbambusek  How about using userID for matching?
https://www.optimizesmart.com/cross-device-tracking-with-user-id-in-google-tag-manager/

Maybe we could generate it in the first step of the reservation?

**Comment by matusficko** [comment]
@pbambusek @jirihelmich @matthijswelle Any update about this please? Thank you!

**Comment by crosenbech** [comment]
@pbambusek Hi Petr, you now have access to Urban Houses tag manager. Please take a look at the setup and edit whatever needs to be done

**Comment by pbambusek** [comment]
@matusficko There is none. When the update is done and ready for testing, we'll inform you.

**Comment by matthijswelle** [comment]
Just to set the expectation, its in our development queue and we have quite a backlog. We are training a new developer and it will take him time to get up to speed and learn GTM. I hope we will find a solution in the coming weeks, but this is sadly proving more complex than we had anticipated due to the payment gateway redirects.

Sorry for this, I wish I had better news, but do not want to set the wrong expectation.

**Comment by matusficko** [comment]
It has been two weeks now. Any update please?

**Comment by matthijswelle** [comment]
Unfortunately not, sorry we have a number of more critical issues which we are working on, so this is currently in the back of the queue :-( Sorry for that.

**Comment by matusficko** [comment]
Adwords and facebook conversion tracking is working correctly using facebook pixel purchase tag and adwords conversions. This is however still very insufficient, since the conversions rarely happen on the first visit. I believe that by populating user-id in analytics with a reservation id when the widget loads might be a neat workaround to pair this different session-ids for now. Isnt it so @pbambusek ?

**Comment by jirihelmich** [comment]
@pbambusek is looking into it this week, I hope, we will come up with a solution.

**Comment by pbambusek** [comment]
@matusficko I've readded the direct Linker plugin usage as it was once before. I'm not sure if it's going to work the same way with GTM as it did once with direct GA integration, but the parameter is added to url and we can test it.

It's scheduled now for deployment and I'll update the issue once it's online.

**Comment by pbambusek** [comment]
It has been deployed. The linker parameter is now being added to the url, which should help to resolve the attribution correctly.

Changelog: https://mewssystems.github.io/public/content/developers/distributor/widget/changelog.html#12072017
