### ISSUE TITLE
Multiple GTM installations

### ISSUE THREAD

**Issue by mariokubik** [MewsSystems/public#22]
I have a question. I just checked Google Tag Manager and Google Analytics, and i see that for your Mews Distributor u are using another GTM and a seperate Google analytics.

For example Boutique hotel Staats:

![image004](https://cloud.githubusercontent.com/assets/20040347/26196519/814b7f34-3bbf-11e7-9a28-abaa1e84ee44.jpg)

Multiple GTM instalations isn't very good according to google. I am trying to figure out how this works.

Could you help me out?

**Comment by pbambusek** [comment]
We keep statistics in our own Google Analytics for global Distributor performance measuring, to have an idea about performance in hotels that don't use Analytics and for ability to build our own statistics on top of the Analytics Api in Commander.

This extension is pretty outdated and doesn't seem to get any attention from authors. For example, for more than year it marks all new GTM containers falsely as invalid only because they have 7 letters not 6. However, those 6 letter IDs were exhausted a long time ago.

Having multiple installations is perfectly fine, if you keep common `dataLayer` name for all of them, which we do. See the documentation for yourself: https://developers.google.com/tag-manager/devguide#multiple-containers
